services:
  - type: web
    name: life-is-short
    runtime: python
    buildCommand: pip install -r requirements-web.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 0
    envVars:
      - key: SECRET_KEY
        generateValue: true
